name: PIPELINE

on:

  push:
  workflow_dispatch:

jobs:
  
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Instalación de librerías necesarias del proyecto
        run: npm install
        
      - name: Escaneo SAST en Sonarcloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    #- name: Comprobación de SonarQube Quality Gate 
      #id: sonarqube-quality-gate-check
      #uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
      #timeout-minutes: 5
      #env:
        #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  Escaneo-SCA-con-DependencyCheck:
    runs-on: ubuntu-latest
    steps:
      - name: 'Hacer el checkout del repositorio'
        uses: actions/checkout@v4
      - name: Escaneo SCA con DependencyCheck
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: moderate
