name: PIPELINE

on:

  push:
  workflow_dispatch:

jobs:
  
  Escaneo-SAST-SONARCLOUD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Escaneo SAST en Sonarcloud
        uses: sonarsource/sonarcloud-github-action@feature-carlosvillanueva
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
