name: PIPELINE

on:

  push:
  workflow_dispatch:

jobs:
  
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    
       
      - name: Escaneo SAST en Sonarcloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    #- name: Comprobación de SonarQube Quality Gate 
      #id: sonarqube-quality-gate-check
      #uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
      #timeout-minutes: 5
      #env:
        #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Instalación de librerías necesarias del proyecto
        run: npm install

      - name: Run Dependency-Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
