name: PIPELINE

on:

  push:
  workflow_dispatch:

jobs:
  
  Escaneo-SAST-SONARCLOUD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Instalación de librerías necesarias del proyecto
        run: npm install
        
      - name: Escaneo SAST en Sonarcloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          #fail-if-qualitygate-fails: true
      
      - name: Comprobación de SonarQube Quality Gate 
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
